### ISSUE TITLE
Maestro card are not validated

### ISSUE THREAD

**Issue by PEM--** [jessepollak/payment#64]
I've tried these 2 Maestro test card number: `5000000000000611` and `5000000000000512` without success.

**Comment by PEM--** [comment]
Note, this card n° are extracted from this website: http://www.securetrading.com/resources/test-card-numbers-2/

**Comment by dpolkovnikov** [comment]
Hello, I have also issue with maestro card type. For example card number that started with 6007 93 should be recognized as maestro, due to maestro rules ( 6.2.1.3 a ) http://www.mastercard.com/rs/merchants/_assets/Maestro_rules.pdf , but regexp for it is not cover 6XXXXX cases.
Could you take a look on it?

**Comment by melloware** [comment]
Can you please try with version 2.4.0 and see if Maestro is still not working?

**Comment by melloware** [comment]
OK.
6007 93 is being reported as HiperCard now.

All the others in this ticket like "5000000000000611" are not being reported as Maesto still as of latest version.

```javascript
{
      type: 'maestro',
      pattern: /^(5018|5020|5038|5078|5[6-9]|6304|6703|6708|6759|676[1-3])/,
      format: defaultFormat,
      length: [12, 13, 14, 15, 16, 17, 18, 19],
      cvcLength: [3],
      luhn: true
  }
```

**Comment by melloware** [comment]
Verified my PR fixes these Maestro cases...

![image](https://user-images.githubusercontent.com/4399574/101259721-8ec50d00-36f8-11eb-8144-96aa599198c2.png)
